on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ZAP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-11-jdk
          wget -nv -O /tmp/ZAP.zip https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          sudo tar -xzvf /tmp/ZAP.zip -C /opt/
          sudo mv /opt/ZAP* /opt/zaproxy
          sudo ln -s /opt/zaproxy/zap.sh /usr/local/bin/zap

      - name: Create ZAP Config File
        run: echo "-config api.addrs.addr.name=.*" > zap-config.txt

      - name: OWASP ZAP Full Scan
        run: zap -config api.addrs.addr.regex=true -config api.disablekey=true -config api.key=your-secret-key -cmd -quickurl "https://mushy-yak-dungarees.cyclic.app" -configFile zap-config.txt
